Centinela/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Centinela.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^usuario/', include('usuario.urls')),
    url(r'^programacion/', include('programacion.urls')),
    url(r'^inspeccion/', include('inspeccion.urls')),
)

urlpatterns += patterns('',
	url(r'^media/(?P<path>.*)$','django.views.static.serve',{'document_root': settings.MEDIA_ROOT,}),)

inspeccion/urls.py
from django.conf.urls import patterns,url

from .views import InspeccionCreateView, InspeccionListView, InspeccionTabularListView

urlpatterns = [

    url(r'^seguimiento/$', InspeccionListView.as_view(), name='inspeccion.inspeccion-list'),
    url(r'^seguimientotabular/$', InspeccionTabularListView.as_view(), name='inspeccion.inspeccion-listTable'),
    url(r'^registrarInspeccion/(?P<id>[0-9]+)/$', InspeccionCreateView.as_view(), name='inspeccion.registrarInspeccion'),
    # url(r'^editarDictamen/(?P<pk>[\w\-]+)/$', DictamenUpdateView.as_view(), name='dictamen.editarDictamen'),
    # url(r'^crearDictamen/$', DictamenCreateView.as_view(), name='dictamen.crearDictamen'),
    # url(r'^detalleDictamen/(?P<idDictamen>[\w\-]+)/$', DictamenDetailView.as_view(), name='Dictamen.Dictamen-detalle'),
    # url(r'^guardarEvaluacion/$', guardarEvaluacion, name='dictamen.guardarEvaluacion'),

]

usuario/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
   # url(r'^registro/$', views.registro_usuario_view, name='accounts.registro'),
    url(r'^$', views.index_view, name='usuario.index'),
    url(r'^login/$', views.login_view, name='usuario.login'),
    url(r'^logout/$', views.logout_view, name='usuario.logout'),
    # url(r'^perfil/$', views.profile_view, name='usuario.perfil'),
    # url(r'^editar_email/$', views.editar_email_view, name='usuario.editar_email'),
    # url(r'^editar_foto/$', views.editar_foto_view, name='usuario.editar_foto'),
    url(r'^editar_clave/$', views.editar_clave_view, name='usuario.editar_clave'),

]

inspeccion/models.py
from django.db import models
from programacion.models import Programacion
# Create your models here.

class Inspeccion(models.Model):
	fechaInicio = models.DateTimeField(auto_now=True)
	longitud = models.CharField(max_length=50, null=True, blank=True)
	latitud = models.CharField(max_length=50,null=True,blank=True)
	programacion = models.ForeignKey(Programacion,related_name="inspeccion_programacion",on_delete=models.PROTECT)
	#fechaTerminacion = models.DateTimeField()
	observacion = models.CharField(max_length=255,null=True, blank=True)

	def __unicode__(self):
		return self.fechaInicio.strftime('%Y-%m-%d %H:%M') + ' - ' + self.programacion.ordenServicio

	class Meta:			
		permissions = (
			("can_see_inspeccion","can see inspeccion"),
		)
		unique_together = [
			["programacion", "fechaInicio"],
		]

	def save(self, *args, **kwargs):
		super(Inspeccion, self).save(*args, **kwargs)
		self.programacion.cerrada=True
		self.programacion.save()

inspeccion/forms.py
from django import forms

from .models import Inspeccion
from programacion.models import Programacion


class InspeccionForm(forms.ModelForm):

	def __init__(self, *args, **kwargs):
		idPro=kwargs.pop('id')
		super(InspeccionForm, self).__init__(*args, **kwargs)

		choices=[(p.id , p.ordenServicio + ' - ' + p.fecha.strftime('%Y-%m-%d') ) for p in Programacion.objects.filter(id=idPro)]
		self.fields['programacion'].choices=choices

	class Meta:
		model = Inspeccion
		fields=('longitud','latitud','programacion','observacion')
		labels = {
			'body':'Texto'
		}

inspeccion/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.views.generic import ListView, UpdateView, CreateView, DeleteView, DetailView
from .models import Inspeccion
from usuario.models import Usuario

from django.contrib import messages
from django.core.urlresolvers import reverse, reverse_lazy
from django.conf import settings

from .forms import InspeccionForm

from django.db.models import Q

class InspeccionCreateView(CreateView):
	model = Inspeccion
	template_name='inspeccion/inspeccion-form.html'
	form_class = InspeccionForm		
	
	def get_success_url(self):
		messages.success(self.request, 'La inspeccion ha sido registrada exitosamente!')
		return reverse('agenda.agenda-list')

	def get_context_data(self,**kwargs):
		context = super(InspeccionCreateView, self).get_context_data(**kwargs)
		context['titulo']='Reportar inspeccion'
		context['nombre_btn']='Reportar'
		context['programacion_id']=self.kwargs['id']
		return context

	def dispatch(self,request,*args, **kwargs):
		if not request.user.has_perms('inspeccion.add_inspeccion'):
			return redirect(settings.LOGIN_URL)
		return super(InspeccionCreateView, self).dispatch(request, *args, **kwargs)

	def form_valid(self,form):
		form.instance.owner = self.request.user
		return super(InspeccionCreateView,self).form_valid(form)

	def get_form_kwargs(self, **kwargs):
		kwargs = super(InspeccionCreateView, self).get_form_kwargs(**kwargs)
		kwargs['initial']['owner'] = self.request.user.id
		return kwargs

	def get_form_kwargs(self):
		kwargs = super(InspeccionCreateView, self).get_form_kwargs()
		kwargs.update({'id': self.kwargs['id']})
		return kwargs

class InspeccionListView(ListView):
	model=Inspeccion
	template_name = 'inspeccion/inspeccion-list.html'
	#paginate_by = 20


	def get_queryset(self):
		usuario= Usuario.objects.get(user=self.request.user)
		query = self.request.GET.get('q', '')
		inspector = self.request.GET.get('cmbInspectores', '')

		qset=(~Q(id=0))

		if query:
			qset=qset & (Q(programacion__ordenServicio__icontains=query) | Q(programacion__nombreProyecto__icontains=query))
		if usuario.coordinador==False:
			qset=qset & (Q(programacion__inspector=usuario))
		else:
			if inspector and inspector !='0':
				objInspector = Usuario.objects.get(pk=inspector)
				if objInspector:
					qset=qset & (Q(programacion__inspector=objInspector))

		queryset = self.model.objects.filter(qset)


		return queryset

	def get_context_data(self, **kwargs):
		ctx = super(InspeccionListView, self).get_context_data(**kwargs)
		ctx['inspectores'] = Usuario.objects.filter(inspector=True)

		inspector = self.request.GET.get('cmbInspectores', '')
		if inspector and inspector !='0':
			ctx['inspectorSeleccionado'] = Usuario.objects.get(pk=inspector)
		else:
			ctx['inspectorSeleccionado'] = None

		ctx['query']= self.request.GET.get('q', '')		
		return ctx

class InspeccionTabularListView(ListView):
	model=Inspeccion
	template_name = 'inspeccion/inspeccion-listTable.html'
	paginate_by = 10


	def get_queryset(self):
		usuario= Usuario.objects.get(user=self.request.user)
		query = self.request.GET.get('q', '')
		inspector = self.request.GET.get('cmbInspectores', '')

		qset=(~Q(id=0))

		if query:
			qset=qset & (Q(programacion__ordenServicio__icontains=query) | Q(programacion__nombreProyecto__icontains=query))
		if usuario.coordinador==False:
			qset=qset & (Q(programacion__inspector=usuario))
		else:
			if inspector and inspector !='0':
				objInspector = Usuario.objects.get(pk=inspector)
				if objInspector:
					qset=qset & (Q(programacion__inspector=objInspector))

		queryset = self.model.objects.filter(qset)


		return queryset

	def get_context_data(self, **kwargs):
		ctx = super(InspeccionTabularListView, self).get_context_data(**kwargs)
		ctx['inspectores'] = Usuario.objects.filter(inspector=True)

		inspector = self.request.GET.get('cmbInspectores', '')
		if inspector and inspector !='0':
			ctx['inspectorSeleccionado'] = Usuario.objects.get(pk=inspector)
		else:
			ctx['inspectorSeleccionado'] = None

		ctx['query']= self.request.GET.get('q', '')		
		return ctx

inspeccion/templates/inspeccion/inspeccion-form.html
{% extends 'base.html' %}

{% block titulo%}Inspeccion{% endblock titulo %}
                            {% block opciones %}
                            <li >
                                <a href="{% url 'usuario.login' %}">Inicio</a>
                            </li >
                            <li class="active">
                                <a href="{% url 'agenda.agenda-list' %}">Agenda</a>
                            </li>                                                    
                            {% endblock opciones %}
{% block navegacion %}
    <li> <a href="{% url 'usuario.index' %}"><i class="fa fa-home"></i> Inicio <span class="divider">/</span></a></li>
    <li><a href="{% url 'agenda.agenda-list' %}"> Agenda <span class="divider">/</span></a></li>
    <li class="active"> </i> Reportar inspeccion </li>
{% endblock navegacion %}
{% block tituloContenido %}
    {{ titulo }}

{% endblock tituloContenido %}


{% block contenido %}
	
	<div class="span10">
		<form id="frmInspeccion" class="form-horizontal" action="" method="post">
			{% csrf_token %}
			{{ form.as_p }}
			<div class="form-actions">
				<button class="btn btn-primary" type="submit" >{{nombre_btn}}</button>
			</div>	
			
		</form>
		<a href="{% url 'agenda.agenda-list' %}"><i class="fa fa-arrow-circle-left fa-2x"></i> Volver al listado de la agenda</a>
	</div>
	<!-- {{ user.usuario.id_empresa.nombre}} -->

{% endblock contenido %}

{% block imports %}
<script type="text/javascript">
    jQuery(document).ready(function(){
        if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(function(position) {
            var pos = {
              lat: position.coords.latitude,
              lng: position.coords.longitude
            };
            $('#id_longitud').val(position.coords.longitude);
            $('#id_latitud').val(position.coords.latitude);

            //infoWindow.setPosition(pos);
            //infoWindow.setContent('Location found.');
            //map.setCenter(pos);
          }, function() {
            //handleLocationError(true, infoWindow, map.getCenter());
          });
        } else {
          // Browser doesn't support Geolocation
          //handleLocationError(false, infoWindow, map.getCenter());
        }

        //$('#id_longitud').val(10);
        //$('#id_latitud').val(20);
    });
</script>
    <script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCu6DgqZcE2iYR0MacArGFz2Mx8lSrVo5E&callback=initMap">
    </script>
{% endblock imports %}

inspeccion/templates/inspeccion/inspeccion-list.html
{% extends 'base.html' %}

{% block titulo%}Seguimiento{% endblock titulo %}
{% block estilos %}
    <style>
      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      #map {
        height: 800px;
      }
      /* Optional: Makes the sample page fill the window. */
/*      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }*/
    </style>
{% endblock estilos%}
                            {% block opciones %}
                            <li >
                                <a href="{% url 'usuario.login' %}">Inicio</a>
                            </li >
                            <li >
                                <a href="{% url 'agenda.agenda-list' %}">Agenda</a>
                            </li>
                                                    
                            {% endblock opciones %}
{% block navegacion %}
<!--    <li>
        <a href="#">Dashboard</a> <span class="divider">/</span>    
    </li>
    <li>
        <a href="#">Settings</a> <span class="divider">/</span> 
    </li> -->
    <li> <a href="{% url 'usuario.index' %}"><i class="fa fa-home"></i> Inicio <span class="divider">/</span></a></li>
    <li class="active"> </i> Seguimiento </li>
{% endblock navegacion %}

{% block tituloContenido %}
    Seguimiento de inspecciones

{% endblock tituloContenido %}

{% block contenido %}
    
        <div class="span12">
            <div class="span12">
                <div class="span6">
                            <!-- <div class="control-group">
                                <div class="controls">
                                    <select class="span6 m-wrap" id="cmbInspecciones">
                                        <option value="0">Mostrar Todas las inspecciones</option>
                                        <option value="1">Mostrar Inpecciones por realizar</option>
                                        <option value="2">Mostrar Inspecciones realizadas</option>
                                    </select>
                                </div>
                            </div> -->
                            <a href="{% url 'inspeccion.inspeccion-listTable' %}"><i class="fa fa-table fa-2x" aria-hidden="true"></i> Vista tabular</a>                    
                </div>
                <div class="span6" style="text-align:right">
                    <form action="." method="GET" >
                        <div class="control-group">
                            <div class="controls">
                                <input class="input-xlarge" id="q" name="q" value="{{ query|escape }}" type="text" placeholder="Buscar por OS o nombre de proyecto..">
                               
                                        {% if user.usuario.coordinador %}
                                
                                    
                                        <select class="span6 m-wrap" id="cmbInspectores" name="cmbInspectores">
                                            {% if inspectorSeleccionado %}
                                                <option value={{inspectorSeleccionado.id}}>
                                                    {{inspectorSeleccionado.nombres}} {{inspectorSeleccionado.apellidos}}
                                                </option>                                               
                                            {% endif %}
                                            <option value=0>[Todos los inspectores...]</option>
                                            
                                            
                                            {% for inspector in inspectores %}
                                                {% if inspector != inspectorSeleccionado %}
                                                <option value={{inspector.id}}>
                                                    {{inspector.nombres}} {{inspector.apellidos}}
                                                </option>
                                                {% endif %}
                                            {% endfor %}    
                                        </select>
                                   
                                
                                        {% endif %}
                                <button class="btn btn-info" type="submit">Buscar</button>        
                            </div>
                        </div>
                    </form>

                </div>
            </div>
            {% if object_list %}
            <div class="span12" id="map">
            </div>
            {% else %}
                <div class="span12 alert alert-warning">
                     <i class="fa fa-info-warning fa-2x"></i> No se encontraron datos   
                </div>
            {% endif %}
        </div>

{% endblock contenido %}

{% block imports %}
<script>
    {% if object_list %}
      function initMap() {
        markers=Array();
        var myLatLng = {lat: 6.477684, lng: -73.966209};

        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 6,
          center: myLatLng
        });
        {% for inspeccion in object_list %}
            {% if inspeccion.latitud %}
            {% if inspeccion.longitud %}
            var contentString = '<b>Orden de Servicio:</b> {{inspeccion.programacion.ordenServicio}}<br/>'+
            '<b>Inspector:</b> {{inspeccion.programacion.inspector.nombres}} '+
            '{{inspeccion.programacion.inspector.apellidos}}<br/><b>Proyecto: </b>'+ 
            '{{inspeccion.programacion.nombreProyecto}}<br/><b>Fecha Inspección: </b>{{ inspeccion.fechaInicio }}<br/>'+
            '<b>Proyecto: </b> {{inspeccion.programacion.nombreProyecto}}';
            

            var infowindow = new google.maps.InfoWindow({
              content: contentString,
              maxWidth: 300
            });
            markers.push(new google.maps.Marker({
              position:{lat: {{inspeccion.latitud}}, lng: {{inspeccion.longitud}}},
              map: map,
              title: String('{{inspeccion.programacion.ordenServicio}}')
            }));
            //markers.push(marker);
            markers[markers.length-1].infowindow = new google.maps.InfoWindow({
                content: contentString
            });
            //  markers[markers.length-1].addListener('click', function() {
            //   infowindow.open(map, markers[markers.length-1]);
            // });
                        google.maps.event.addListener(markers[markers.length-1], 'click', function() {
                                var info=this.infowindow;
                                info.open(map, this);
                             
                        });
            {% endif %}
            {% endif %}
        {% endfor %}
      }
    {% endif %}  
</script>
    <script type="text/javascript"
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCu6DgqZcE2iYR0MacArGFz2Mx8lSrVo5E&callback=initMap">
    </script>


{% endblock imports %}

inspeccion/templates/inspeccion/inspeccion-listTable.html
{% extends 'base.html' %}

{% block titulo%}Seguimiento{% endblock titulo %}
{% block estilos %}
    <style>
      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      #map {
        height: 800px;
      }
      /* Optional: Makes the sample page fill the window. */
/*      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }*/
    </style>
{% endblock estilos%}
                            {% block opciones %}
                            <li >
                                <a href="{% url 'usuario.login' %}">Inicio</a>
                            </li >
                            <li >
                                <a href="{% url 'agenda.agenda-list' %}">Agenda</a>
                            </li>
                                                    
                            {% endblock opciones %}
{% block navegacion %}
<!--    <li>
        <a href="#">Dashboard</a> <span class="divider">/</span>    
    </li>
    <li>
        <a href="#">Settings</a> <span class="divider">/</span> 
    </li> -->
    <li> <a href="{% url 'usuario.index' %}"><i class="fa fa-home"></i> Inicio <span class="divider">/</span></a></li>
    <li class="active"><a href="{% url 'inspeccion.inspeccion-list' %}"> Seguimiento <span class="divider">/</span></a></li>
    <li class="active"> Seguimiento Tabular </li>
{% endblock navegacion %}

{% block tituloContenido %}
    Seguimiento de inspecciones - Vista Tabular

{% endblock tituloContenido %}

{% block contenido %}
    
        <div class="span12">
            <div class="span12">
                <div class="span6">
                            <!-- <div class="control-group">
                                <div class="controls">
                                    <select class="span6 m-wrap" id="cmbInspecciones">
                                        <option value="0">Mostrar Todas las inspecciones</option>
                                        <option value="1">Mostrar Inpecciones por realizar</option>
                                        <option value="2">Mostrar Inspecciones realizadas</option>
                                    </select>
                                </div>
                            </div> -->
                            <a href="{% url 'inspeccion.inspeccion-list' %}"><i class="fa fa-map fa-2x" aria-hidden="true"></i></i> Vista Mapa</a>                    
                </div>
                <div class="span6" style="text-align:right">
                    <form action="." method="GET" >
                        <div class="control-group">
                            <div class="controls">
                                <input class="input-xlarge" id="q" name="q" value="{{ query|escape }}" type="text" placeholder="Buscar por OS o nombre de proyecto..">
                               
                                        {% if user.usuario.coordinador %}
                                
                                    
                                        <select class="span6 m-wrap" id="cmbInspectores" name="cmbInspectores">
                                        	{% if inspectorSeleccionado %}
                                           		<option value={{inspectorSeleccionado.id}}>
                                            		{{inspectorSeleccionado.nombres}} {{inspectorSeleccionado.apellidos}}
                                            	</option>                                        		
                                        	{% endif %}
                                        	<option value=0>[Todos los inspectores...]</option>
                                        	
                                            
                                            {% for inspector in inspectores %}
                                            	{% if inspector != inspectorSeleccionado %}
                                            	<option value={{inspector.id}}>
                                            		{{inspector.nombres}} {{inspector.apellidos}}
                                            	</option>
                                            	{% endif %}
                                            {% endfor %}	
                                        </select>
                                   
                                
                                        {% endif %}
                                <button class="btn btn-info" type="submit">Buscar</button>        
                            </div>
                        </div>
                    </form>

                </div>
            </div>
            {% if object_list %}
 			<table class="table table-hover">
                <thead>
                    <tr>
                    	<th width="10%">GPS disponible</th>
                    	<th width="10%">Orden de servicio</th>
                    	<th width="25%">Proyecto</th>
                    	<th width="10%">Inspector</th>
                        <th width="15%">Fecha programada</th>
                        <th width="15%">Fecha ejecucion</th>
                        <th width="20%">observaciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for inspeccion in object_list %}
                        <tr>
                        	<td>
                        		{% if inspeccion.latitud %}
	                        		{% if inspeccion.longitud %}
	                        			<font color="green"><b>Si</b></font>
	                        		{% else %}
	                        			<font color="red"><b>No</b></font>
	                        		{% endif %}
	                        	{% else %}
	                        		<font color="red"><b>No</b></font>
                        		{% endif %}
                        	</td>
                            <td>{{ inspeccion.programacion.ordenServicio }}</td>
                            <td>{{ inspeccion.programacion.nombreProyecto }}</td>
                            <td>{{ inspeccion.programacion.inspector.nombres }} {{ inspeccion.programacion.inspector.apellidos }}</td>
                            <td>{{ inspeccion.fechaInicio }}</td>
                            <td>{{ inspeccion.programacion.fecha }}</td>
                            <td>{{ inspeccion.observacion }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <!--Paginacion de los registros-->
            {% if is_paginated %}
            <ul class="pagination">

                    {% if page_obj.has_previous %}
                        <li><a href="?page={{ page_obj.previous_page_number }}">anterior</a></li>
                    {% endif %}
                    {% for num in page_obj.paginator.page_range %}
                        {% ifequal num page_obj.number %}
                            <li><a href="#" class="active">{{ num }}</a></li>
                        {% else %}
                            <li><a href="?page={{ num }}"> {{ num }}</a></li>
                        {% endifequal %} 
                    {% endfor %}
                
                    {% if page_obj.has_next %}
                        <li><a href="?page={{ page_obj.next_page_number }}">siguiente</a></li>
                    {% endif %}
            </ul>
            {% endif %}
    {% else %}
        <div class="span12 alert alert-warning">
             <i class="fa fa-warning fa-2x"></i> No se encontraron datos   
        </div>
    {% endif %}
        </div>

{% endblock contenido %}